# Generated by Django 4.1.1 on 2022-09-09 07:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("Blog", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="article",
            name="subtract",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="article",
            name="text",
            field=models.TextField(blank=True, null=True),
        ),
    ]
