# Generated by Django 4.1.1 on 2022-09-10 08:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("Blog", "0002_alter_article_subtract_alter_article_text"),
    ]

    operations = [
        migrations.RemoveField(model_name="article", name="subtract",),
        migrations.RemoveField(model_name="article", name="text",),
        migrations.AddField(
            model_name="article",
            name="active",
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name="article",
            name="content",
            field=models.TextField(blank=True, null=True),
        ),
    ]
