# Generated by Django 4.1.1 on 2022-09-10 08:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("Blog", "0004_remove_article_active_article_subtract_and_more"),
    ]

    operations = [
        migrations.RemoveField(model_name="article", name="subtract",),
        migrations.AddField(
            model_name="article",
            name="active",
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name="article",
            name="content",
            field=models.TextField(blank=True, null=True),
        ),
    ]
