# Generated by Django 4.1.1 on 2022-09-07 09:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fruit', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='fruit',
            name='buy',
            field=models.BooleanField(default=True),
            preserve_default=False,
        ),
    ]
